"""make vendor phone unique

Revision ID: 514a1ac4d142
Revises: 
Create Date: 2026-09-02 17:33:23.162341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '514a1ac4d142'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('document_type', sa.String(length=50), server_default=sa.text("'INVOICE'::character varying"), nullable=False),
    sa.Column('status', sa.String(length=30), server_default=sa.text("'UPLOADED'::character varying"), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status::text = ANY (ARRAY['UPLOADED'::character varying, 'OCR_PROCESSING'::character varying, 'OCR_COMPLETED'::character varying, 'EXTRACTION_PROCESSING'::character varying, 'EXTRACTION_COMPLETED'::character varying, 'FAILED'::character varying]::text[])", name='documents_status_check'),
    sa.PrimaryKeyConstraint('id', name='documents_pkey')
    )
    op.create_index('idx_documents_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.alter_column('vendors', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_unique_constraint(None, 'vendors', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vendors', type_='unique')
    op.alter_column('vendors', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_document_type', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
